//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResvoyageMobileApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResvoyageMobileApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string APP_CAR {
            get {
                return ResourceManager.GetString("APP_CAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        internal static string APP_FLIGHT {
            get {
                return ResourceManager.GetString("APP_FLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string APP_FOR {
            get {
                return ResourceManager.GetString("APP_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string APP_HOTEL {
            get {
                return ResourceManager.GetString("APP_HOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string APP_SELECT {
            get {
                return ResourceManager.GetString("APP_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin.
        /// </summary>
        internal static string FD_CABIN {
            get {
                return ResourceManager.GetString("FD_CABIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight duration.
        /// </summary>
        internal static string FD_FLIGHT_DURATION {
            get {
                return ResourceManager.GetString("FD_FLIGHT_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight number.
        /// </summary>
        internal static string FD_FLIGHT_NUMBER {
            get {
                return ResourceManager.GetString("FD_FLIGHT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layover.
        /// </summary>
        internal static string FD_LAYOVER {
            get {
                return ResourceManager.GetString("FD_LAYOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operated by:.
        /// </summary>
        internal static string FD_OPERATED_BY {
            get {
                return ResourceManager.GetString("FD_OPERATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airlines.
        /// </summary>
        internal static string FF_AIRLINES {
            get {
                return ResourceManager.GetString("FF_AIRLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheapest.
        /// </summary>
        internal static string FF_CHEAPEST {
            get {
                return ResourceManager.GetString("FF_CHEAPEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest.
        /// </summary>
        internal static string FF_EARLIEST {
            get {
                return ResourceManager.GetString("FF_EARLIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FF_FILTERS {
            get {
                return ResourceManager.GetString("FF_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inound Departure.
        /// </summary>
        internal static string FF_INBOUND_DEPARTURE {
            get {
                return ResourceManager.GetString("FF_INBOUND_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inound Arrival.
        /// </summary>
        internal static string FF_INOUND_ARRIVAL {
            get {
                return ResourceManager.GetString("FF_INOUND_ARRIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonstop.
        /// </summary>
        internal static string FF_NONSTOP {
            get {
                return ResourceManager.GetString("FF_NONSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Stop.
        /// </summary>
        internal static string FF_ONESTOP {
            get {
                return ResourceManager.GetString("FF_ONESTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Arrival.
        /// </summary>
        internal static string FF_OUTBOUND_ARRIVAL {
            get {
                return ResourceManager.GetString("FF_OUTBOUND_ARRIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Departure.
        /// </summary>
        internal static string FF_OUTBOUND_DEPARTURE {
            get {
                return ResourceManager.GetString("FF_OUTBOUND_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickest.
        /// </summary>
        internal static string FF_QUICKEST {
            get {
                return ResourceManager.GetString("FF_QUICKEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select airlines.
        /// </summary>
        internal static string FF_SELECT_AIRLINES {
            get {
                return ResourceManager.GetString("FF_SELECT_AIRLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops.
        /// </summary>
        internal static string FF_STOPS {
            get {
                return ResourceManager.GetString("FF_STOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Range.
        /// </summary>
        internal static string FF_TIME_RANGE {
            get {
                return ResourceManager.GetString("FF_TIME_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2+ Stops.
        /// </summary>
        internal static string FF_TWOSTOPS {
            get {
                return ResourceManager.GetString("FF_TWOSTOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin.
        /// </summary>
        internal static string FR_CABIN {
            get {
                return ResourceManager.GetString("FR_CABIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string FR_DURATION {
            get {
                return ResourceManager.GetString("FR_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        internal static string FR_PASSENGER {
            get {
                return ResourceManager.GetString("FR_PASSENGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers.
        /// </summary>
        internal static string FR_PASSENGERS {
            get {
                return ResourceManager.GetString("FR_PASSENGERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string FR_TRANSFER {
            get {
                return ResourceManager.GetString("FR_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioning.
        /// </summary>
        internal static string HD_AIRCONDITIONING {
            get {
                return ResourceManager.GetString("HD_AIRCONDITIONING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string HD_BAR {
            get {
                return ResourceManager.GetString("HD_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string HD_BREAKBAST {
            get {
                return ResourceManager.GetString("HD_BREAKBAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string HD_DESCRIPTION {
            get {
                return ResourceManager.GetString("HD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Cancellation.
        /// </summary>
        internal static string HD_FREE_CANCELLATION {
            get {
                return ResourceManager.GetString("HD_FREE_CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        internal static string HD_GYM {
            get {
                return ResourceManager.GetString("HD_GYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdryer.
        /// </summary>
        internal static string HD_HAIRDRYER {
            get {
                return ResourceManager.GetString("HD_HAIRDRYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Amenities.
        /// </summary>
        internal static string HD_HOTEL_AMENITIES {
            get {
                return ResourceManager.GetString("HD_HOTEL_AMENITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housekeeping.
        /// </summary>
        internal static string HD_HOUSEKEEPING {
            get {
                return ResourceManager.GetString("HD_HOUSEKEEPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Description.
        /// </summary>
        internal static string HD_LOCATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("HD_LOCATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        internal static string HD_OTHER_INFORMATION {
            get {
                return ResourceManager.GetString("HD_OTHER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        internal static string HD_PARKING {
            get {
                return ResourceManager.GetString("HD_PARKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Friendly.
        /// </summary>
        internal static string HD_PET_FRIENDLY {
            get {
                return ResourceManager.GetString("HD_PET_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string HD_POOL {
            get {
                return ResourceManager.GetString("HD_POOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string HD_RESTAURANT {
            get {
                return ResourceManager.GetString("HD_RESTAURANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Amenities.
        /// </summary>
        internal static string HD_ROOM_AMENITIES {
            get {
                return ResourceManager.GetString("HD_ROOM_AMENITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Service.
        /// </summary>
        internal static string HD_ROOM_SERVICE {
            get {
                return ResourceManager.GetString("HD_ROOM_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spa.
        /// </summary>
        internal static string HD_SPA {
            get {
                return ResourceManager.GetString("HD_SPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string HD_TV {
            get {
                return ResourceManager.GetString("HD_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi Fi.
        /// </summary>
        internal static string HD_WiFi {
            get {
                return ResourceManager.GetString("HD_WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains.
        /// </summary>
        internal static string HF_CHAINS {
            get {
                return ResourceManager.GetString("HF_CHAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Name.
        /// </summary>
        internal static string HF_HOTEL_NAME {
            get {
                return ResourceManager.GetString("HF_HOTEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string HF_PRICE {
            get {
                return ResourceManager.GetString("HF_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Rating.
        /// </summary>
        internal static string HF_STAR_RATING {
            get {
                return ResourceManager.GetString("HF_STAR_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        internal static string HF_STARS {
            get {
                return ResourceManager.GetString("HF_STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hotels found..
        /// </summary>
        internal static string HR_NO_HOTELS_FOUND {
            get {
                return ResourceManager.GetString("HR_NO_HOTELS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No star rating.
        /// </summary>
        internal static string HR_NO_STAR_RATING {
            get {
                return ResourceManager.GetString("HR_NO_STAR_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per night, per room.
        /// </summary>
        internal static string HR_PER_NIGHT_PER_ROOM {
            get {
                return ResourceManager.GetString("HR_PER_NIGHT_PER_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Room.
        /// </summary>
        internal static string HS_ADD_ROOM {
            get {
                return ResourceManager.GetString("HS_ADD_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in date.
        /// </summary>
        internal static string HS_CHECK_IN_DATE {
            get {
                return ResourceManager.GetString("HS_CHECK_IN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in location.
        /// </summary>
        internal static string HS_CHECK_IN_LOCATION {
            get {
                return ResourceManager.GetString("HS_CHECK_IN_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out date.
        /// </summary>
        internal static string HS_CHECK_OUT_DATE {
            get {
                return ResourceManager.GetString("HS_CHECK_OUT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chid.
        /// </summary>
        internal static string HS_CHLD {
            get {
                return ResourceManager.GetString("HS_CHLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations found..
        /// </summary>
        internal static string HS_NO_LOCATIONS_FOUND {
            get {
                return ResourceManager.GetString("HS_NO_LOCATIONS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Room.
        /// </summary>
        internal static string HS_REMOVE_ROOM {
            get {
                return ResourceManager.GetString("HS_REMOVE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string HS_ROOM {
            get {
                return ResourceManager.GetString("HS_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string HS_ROOMS {
            get {
                return ResourceManager.GetString("HS_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Hotels.
        /// </summary>
        internal static string HS_SEARCH_HOTELS {
            get {
                return ResourceManager.GetString("HS_SEARCH_HOTELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.o..
        /// </summary>
        internal static string HS_Y_O {
            get {
                return ResourceManager.GetString("HS_Y_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string RD_BED {
            get {
                return ResourceManager.GetString("RD_BED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beds.
        /// </summary>
        internal static string RD_BEDS {
            get {
                return ResourceManager.GetString("RD_BEDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before.
        /// </summary>
        internal static string RD_BEFORE {
            get {
                return ResourceManager.GetString("RD_BEFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string RD_NIGHT {
            get {
                return ResourceManager.GetString("RD_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nights.
        /// </summary>
        internal static string RD_NIGHTS {
            get {
                return ResourceManager.GetString("RD_NIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string RD_RESERVE {
            get {
                return ResourceManager.GetString("RD_RESERVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total rate for.
        /// </summary>
        internal static string RD_TOTAL_FARE_FOR {
            get {
                return ResourceManager.GetString("RD_TOTAL_FARE_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticket.
        /// </summary>
        internal static string SC_TICKET {
            get {
                return ResourceManager.GetString("SC_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets.
        /// </summary>
        internal static string SC_TICKETS {
            get {
                return ResourceManager.GetString("SC_TICKETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string SF_ADULT {
            get {
                return ResourceManager.GetString("SF_ADULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        internal static string SF_ADULTS {
            get {
                return ResourceManager.GetString("SF_ADULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 12 years old.
        /// </summary>
        internal static string SF_ADULTS_YEARS {
            get {
                return ResourceManager.GetString("SF_ADULTS_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SF_APPLY {
            get {
                return ResourceManager.GetString("SF_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin Class.
        /// </summary>
        internal static string SF_CABIN_CLASS {
            get {
                return ResourceManager.GetString("SF_CABIN_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin:.
        /// </summary>
        internal static string SF_CABIN_COLON {
            get {
                return ResourceManager.GetString("SF_CABIN_COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string SF_CHILD {
            get {
                return ResourceManager.GetString("SF_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string SF_CHILDREN {
            get {
                return ResourceManager.GetString("SF_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-12 years old.
        /// </summary>
        internal static string SF_CHILDREN_YEARS {
            get {
                return ResourceManager.GetString("SF_CHILDREN_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string SF_DEPARTURE {
            get {
                return ResourceManager.GetString("SF_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        internal static string SF_DEPARTURE_DATE {
            get {
                return ResourceManager.GetString("SF_DEPARTURE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure of second segment.
        /// </summary>
        internal static string SF_DEPARTURE_SECOND_SEGMENT {
            get {
                return ResourceManager.GetString("SF_DEPARTURE_SECOND_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure of third segment.
        /// </summary>
        internal static string SF_DEPARTURE_THIRD_SEGMENT {
            get {
                return ResourceManager.GetString("SF_DEPARTURE_THIRD_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string SF_DESTINATION {
            get {
                return ResourceManager.GetString("SF_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination of second segment.
        /// </summary>
        internal static string SF_DESTINATION_SECOND_SEGMENT {
            get {
                return ResourceManager.GetString("SF_DESTINATION_SECOND_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination of third segment.
        /// </summary>
        internal static string SF_DESTINATION_THIRD_SEGMENT {
            get {
                return ResourceManager.GetString("SF_DESTINATION_THIRD_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string SF_DOCUMENTS {
            get {
                return ResourceManager.GetString("SF_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string SF_FROM {
            get {
                return ResourceManager.GetString("SF_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From of second segment.
        /// </summary>
        internal static string SF_FROM_SECOND_SEGMENT {
            get {
                return ResourceManager.GetString("SF_FROM_SECOND_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From of third segment.
        /// </summary>
        internal static string SF_FROM_THIRD_SEGMENT {
            get {
                return ResourceManager.GetString("SF_FROM_THIRD_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        internal static string SF_INFANT {
            get {
                return ResourceManager.GetString("SF_INFANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infants.
        /// </summary>
        internal static string SF_INFANTS {
            get {
                return ResourceManager.GetString("SF_INFANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-2 years old.
        /// </summary>
        internal static string SF_INFANTS_YEARS {
            get {
                return ResourceManager.GetString("SF_INFANTS_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-City.
        /// </summary>
        internal static string SF_MULTI_CITY {
            get {
                return ResourceManager.GetString("SF_MULTI_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No airports found.
        /// </summary>
        internal static string SF_NO_AIRPORTS_FOUND {
            get {
                return ResourceManager.GetString("SF_NO_AIRPORTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Way.
        /// </summary>
        internal static string SF_ONE_WAY {
            get {
                return ResourceManager.GetString("SF_ONE_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular places.
        /// </summary>
        internal static string SF_POPULAR_PLACES {
            get {
                return ResourceManager.GetString("SF_POPULAR_PLACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string SF_RETURN {
            get {
                return ResourceManager.GetString("SF_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        internal static string SF_RETURN_DATE {
            get {
                return ResourceManager.GetString("SF_RETURN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Trip.
        /// </summary>
        internal static string SF_ROUND_TRIP {
            get {
                return ResourceManager.GetString("SF_ROUND_TRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Flights.
        /// </summary>
        internal static string SF_SEARCH_FLIGHTS {
            get {
                return ResourceManager.GetString("SF_SEARCH_FLIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  fields are mandatory!.
        /// </summary>
        internal static string SF_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("SF_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  field is mandatory!.
        /// </summary>
        internal static string SF_VALIDATION_ERROR_SINGLE {
            get {
                return ResourceManager.GetString("SF_VALIDATION_ERROR_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flights found..
        /// </summary>
        internal static string SR_NO_FLIGHTS_FOUND {
            get {
                return ResourceManager.GetString("SR_NO_FLIGHTS_FOUND", resourceCulture);
            }
        }
    }
}
